### ISSUE TITLE
get AttributeError: grad_fn when use make_dot

### ISSUE THREAD

**Issue by Pinnh** [szagoruyko/functional-zoo#14]
when I use following code to visualize the torch pretrained resnet18 model, I get AttributeError: grad_fn, at line: add_nodes(var.grad_fn)
```
input=torch.randn(1,3,224,224)  
model=models.resnet18(pretrained=True)
for param in model.parameters():
     param.requires_grad = True
params = model.state_dict()
y=model(Variable(input))
print y
dot=make_dot(y, params)
```

**Comment by szagoruyko** [comment]
@Pinnh that's because `model.state_dict()` returns a dict of tensors, whereas `make_dot` expects a dict of Variables. I don't think there's a method that returns such dict for a model, so for now the best solution would probably be to make the `params` argument optional.
