### ISSUE TITLE
Issue with output torch Variable in visualize.py throwing an attribute error (grad_fn)

### ISSUE THREAD

**Issue by ritvikshrivastava** [szagoruyko/functional-zoo#19]
Hey, so I am facing the same issue as issue #14  . Although what you said is correct about the `model.state_dict()`, the error about grad_fn arises from `var`, which is the output variable of the model and not the params dictionary. Any ideas on how to fix this?

As for the `model.state_dict()` part, I think it can be converted to the required `(name, Variable)` format using;

```
params = model.state_dict()
for k in sorted(params.keys()):
	v = params[k]
	params[k] = autograd.Variable(v, requires_grad=True)
```
I printed this out, and it seemed fine. 

Need help to remove the var.grad_fn attribute error though. 
Thanks.

**Comment by sydney0zq** [comment]
Same problem, can anyone help me out about this?

**Comment by datlife** [comment]
I did not pass the params and it works:

```
model = alexnet(pretrained=True)

# generate random noise
inputs = Variable(torch.randn(1, 3, 224, 224))

# predict
y = model(inputs)
print(y)
make_dot(y)
```

**Comment by szagoruyko** [comment]
see https://github.com/szagoruyko/pytorchviz how to use make_dot with modules
