### ISSUE TITLE
Where is the wide-resnet-50-2-export.pth?

### ISSUE THREAD

**Issue by dzk9528** [szagoruyko/functional-zoo#22]
I try to export the wide-resnet-50-2 in tensorflow by using your code in 
https://github.com/szagoruyko/functional-zoo/blob/master/wide-resnet-50-2-export.ipynb
But it seems like I cannot find out where to download the paramters, can you tell me where the .pth is ?

**Comment by jennyzu** [comment]
How did you manage to download the parameters for tensorflow? I see only link for Torch.
