### ISSUE TITLE
Show how to use models for fine-tuning

### ISSUE THREAD

**Issue by jph00** [szagoruyko/functional-zoo#4]
The readme explains that all the models listed so far have bn params integrated into the conv weights, for performance, thus making these models not useful for fine-tuning. Fine-tuning is, perhaps, the most common thing that people use pre-trained models for, so it would be great it you could do one of the following:

- Explain how to separate out the bn params in the existing models
- Show how to re-create the models so that others can do so without the bn param integration
- Make every model available in both integrated and standard format

Many thanks for this great project!

**Comment by szagoruyko** [comment]
Thanks @jph00, that's a great idea. I already have some finetuning code in pytorch that I did for https://github.com/szagoruyko/attention-transfer for CUB-2011 and Scenes, will make an example sometime soon.

**Comment by jph00** [comment]
Many thanks for looking at this. I'm starting teaching part 2 of http://course.fast.ai in <2 weeks and would love to use some of these in my teaching - especially fast style transfer! :)

**Comment by jph00** [comment]
Just checking in - any progress on separating out the BN params so we can use these models for fine-tuning? Sorry to trouble you!...
